export const MOVIE_QUERY = 'MOVIE_QUERY';
export const MOVIE_SEARCH = 'MOVIE_SEARCH';
export const MOVIE_SEARCH_PENDING = 'MOVIE_SEARCH_PENDING';
export const MOVIE_SEARCH_FULFILLED = 'MOVIE_SEARCH_FULFILLED';
export const MOVIE_SEARCH_REJECTED = 'MOVIE_SEARCH_REJECTED';


